# param error test
# --output:start
# --output:end

func test(a, b, c) {}
func test2(){}
func test3(t...){}
func test4(a, b = 5){}

test(5, 6)
test2()
test3(1, 2, 3)
test4(1)
